import React, { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'

const SECTIONS = [
  {
    icon: '⊞',
    title: 'Overview',
    path: '/',
    summary: 'Your security command centre — shows everything at a glance.',
    details: [
      { heading: 'Live metrics', body: 'CPU, RAM, disk usage and temperature are shown in real time via WebSocket. Values turn red when they breach safe thresholds (CPU > 80 %, RAM > 85 %, temp > 75 °C).' },
      { heading: 'AI Engine Status', body: 'Six AI modules are shown with green/yellow/grey indicators: Anomaly Detector, IDS Engine, File Integrity Monitor, Honeypot, Threat Predictor, and Federated Learning. Yellow means the module is initialising; grey means no data yet.' },
      { heading: 'Threat Score Chart', body: 'An area chart of the rolling threat score over time. Spikes indicate periods of elevated attack activity detected by the IDS or anomaly engine.' },
      { heading: 'CPU / Network Charts', body: 'Scrolling 20-point history of CPU % and network throughput (recv/sent). Useful for spotting sustained load caused by attacks or cryptominers.' },
      { heading: 'Recent Alerts & Processes', body: 'The last five security alerts and the top CPU-consuming processes, so you can correlate suspicious processes with alerts without leaving the page.' },
    ],
  },
  {
    icon: '🔔',
    title: 'Alerts',
    path: '/alerts',
    summary: 'Every threat event generated by the AI engines, in one list.',
    details: [
      { heading: 'Severity filter', body: 'Use the pill buttons to filter by Critical, High, Medium, Low, or Info. The badge on each pill shows how many unresolved alerts exist at that level.' },
      { heading: 'Threat Score Ring', body: 'The ring on the left of each alert shows a 0–10 threat score: red (≥ 8), yellow (≥ 6), green (< 6). This is calculated by the IDS engine from attack signatures and behavioural patterns.' },
      { heading: 'ACK / CLOSE', body: 'Acknowledge an alert to mark it as seen without closing it. Close (resolve) an alert once you have investigated and handled it. Resolved alerts are hidden by default — enable "Show resolved" to see them.' },
      { heading: 'Source IP & geo', body: 'If the IDS identified a source IP, it is shown alongside the country code so you can quickly judge whether traffic is expected.' },
    ],
  },
  {
    icon: '🧠',
    title: 'AI Insights',
    path: '/ai',
    summary: 'Predictive threat forecasting and log correlation from the ML models.',
    details: [
      { heading: 'Forecast tab', body: 'The AI Threat Predictor analyses historical attack patterns to predict the threat level for each of the next 24 hours. The area chart shows the predicted score (0–100 %). Overall risk and peak hour are highlighted above the chart.' },
      { heading: 'Recommendations', body: 'The predictor generates plain-English recommendations based on its forecast, such as "Consider tightening SSH rate limits during the 02:00–04:00 window".' },
      { heading: 'Log Insights tab', body: 'The Log Intelligence engine correlates raw system logs to surface multi-event patterns, for example: "50 failed SSH logins from 3 IPs in 10 minutes". Each insight shows affected IPs and a severity rating.' },
      { heading: 'IDS Alerts tab', body: 'Raw IDS detections with MITRE ATT&CK technique tags and exact threat scores. Use this for deep investigation when you want more technical detail than the Alerts panel shows.' },
    ],
  },
  {
    icon: '🌐',
    title: 'Network',
    path: '/network',
    summary: 'Live connection table, bandwidth stats, and suspicious connection alerts.',
    details: [
      { heading: 'Stat cards', body: 'Total, Established, Listening, and Suspicious connection counts refresh every 8 seconds. A red Suspicious count means at least one connection matches a known bad pattern (port scanning, unusual destination, etc.).' },
      { heading: 'Bandwidth', body: 'Inbound and outbound data rates sourced from the live WebSocket stream. High outbound from a process you don\'t recognise may indicate data exfiltration.' },
      { heading: 'Suspicious connections panel', body: 'When suspicious connections are detected, they surface above the table in a red panel so they are impossible to miss. Shows remote IP, destination port, protocol, and status.' },
      { heading: 'Connection table', body: 'Up to 30 active connections with local address, remote address, status, protocol, and service label. Suspicious rows are highlighted in red.' },
    ],
  },
  {
    icon: '📄',
    title: 'File Integrity',
    path: '/fim',
    summary: 'AI-powered monitoring of critical system files for unauthorised changes.',
    details: [
      { heading: 'How it works', body: 'The FIM engine builds SHA-256 baseline hashes of critical files (e.g. /etc/passwd, /etc/ssh/sshd_config, web server configs). It compares live hashes against the baseline every few minutes.' },
      { heading: 'Severity', body: 'Changes are scored by the AI: system binary modifications are Critical, config changes are High, log rotation is Info. This avoids alert fatigue from expected changes.' },
      { heading: 'Rebuild Baseline', body: 'Click "Rebuild Baseline" after you intentionally change a monitored file (e.g. after a legitimate config edit) to update the reference hashes and clear the alert.' },
      { heading: 'Events list', body: 'Each event shows the file path, change type (modified / added / deleted), old and new hash, and the AI severity assessment.' },
    ],
  },
  {
    icon: '🐞',
    title: 'Vulnerabilities',
    path: '/vulns',
    summary: 'CVE scanning of installed packages with AI-powered risk prioritisation.',
    details: [
      { heading: 'CVE scan', body: 'The scanner reads installed package versions and matches them against the NVD / OSV databases. It identifies packages with known vulnerabilities and fetches CVSS scores.' },
      { heading: 'AI prioritisation', body: 'A raw CVSS score does not account for whether the vulnerable service is exposed, whether exploits are public, or how critical the package is to your deployment. The AI layer re-ranks findings for your specific context.' },
      { heading: 'Fix commands', body: 'Each vulnerability includes the recommended remediation command (e.g. apt upgrade <package>=<version>). You can copy these directly to your terminal.' },
      { heading: 'Scan now', body: 'Scans run automatically on startup and periodically. Use "Scan Now" to trigger an immediate re-scan after applying patches to verify they resolved the findings.' },
    ],
  },
  {
    icon: '🛡',
    title: 'Hardening',
    path: '/hardening',
    summary: 'CIS-inspired configuration audit across SSH, firewall, kernel, SUID, sudo, services, and more.',
    details: [
      { heading: 'Hardening Score', body: 'Scored 0–100 proportionally: each failed check deducts a weighted share of the total possible points. A score of 100 means every check passed. Grade A+ = 95–100, A = 85–94, B = 70–84, C = 55–69, D = 40–54, F < 40.' },
      { heading: 'AI Assessment', body: 'The AI generates a plain-English summary of your security posture and a ranked list of the most impactful recommendations to action first.' },
      { heading: 'Category tabs', body: 'Filter findings by category: SSH configuration, Firewall rules, Kernel parameters, SUID binaries, sudo policy, User accounts, Running services, File permissions.' },
      { heading: 'Auto Fix', body: 'Checks marked with ⚡ Auto Fix have a safe, reversible remediation command. Clicking Auto Fix runs the command directly on the system (the service runs as root, so no sudo prompt). Always review the shown command before applying.' },
      { heading: 'Show passed', body: 'By default, only failed checks are shown to reduce noise. Enable "Show passed" to see the full audit log including everything that is correctly configured.' },
    ],
  },
  {
    icon: '🍯',
    title: 'Honeypot',
    path: '/honeypot',
    summary: 'Decoy services that lure and fingerprint attackers probing your system.',
    details: [
      { heading: 'How it works', body: 'The honeypot runs lightweight fake services (SSH banner, HTTP, Telnet) on non-standard ports. Any connection to these ports is inherently suspicious — no legitimate user should be contacting them.' },
      { heading: 'Attacker fingerprinting', body: 'The AI analyses the commands and payloads attackers send to classify their tools, skill level, and likely goal (credential brute force, web shell, botnet recruitment, etc.).' },
      { heading: 'Auto block', body: 'IPs that interact with the honeypot can be automatically added to the firewall blocklist. This is configurable in Settings.' },
      { heading: 'Session replay', body: 'Full interaction logs are captured so you can review exactly what an attacker typed or sent. Useful for threat intelligence and understanding attack techniques targeting your hardware.' },
    ],
  },
  {
    icon: '⊗',
    title: 'Blocked IPs',
    path: '/blocked',
    summary: 'Manage the firewall IP blocklist — view, add, and remove blocked addresses.',
    details: [
      { heading: 'Automatic blocks', body: 'IPs can be added automatically by the IDS or Honeypot when they exceed a threat threshold. Auto-blocked IPs are tagged "Auto" in the source column.' },
      { heading: 'Manual block', body: 'Enter any IPv4 address and an optional reason to add it to the firewall immediately. Useful for blocking IPs identified through external threat intelligence.' },
      { heading: 'Unblock', body: 'Click Unblock on any row to remove the IP from the firewall. The change takes effect immediately. Use this if a legitimate IP was blocked by mistake.' },
      { heading: 'Under the hood', body: 'Blocks are applied via iptables (or nftables depending on your OS). The dashboard manages the rules — you do not need to touch the command line.' },
    ],
  },
  {
    icon: '⚙',
    title: 'Settings',
    path: '/settings',
    summary: 'Configure AI thresholds, notifications, auto-response, and account security.',
    details: [
      { heading: 'AI Sensitivity', body: 'Adjust the anomaly detection and IDS thresholds. Lower sensitivity = fewer false positives but may miss subtle attacks. Higher sensitivity = catches more threats but may generate more noise.' },
      { heading: 'Auto-block threshold', body: 'Set the threat score (1–10) above which an attacking IP is automatically added to the firewall. Default is 8 (Critical). Reduce to 6 to block High-severity sources as well.' },
      { heading: 'Federated Learning', body: 'When enabled, your device contributes anonymised model gradients to a shared threat intelligence pool and receives updates in return — improving detection of novel attacks across the fleet without sharing raw data.' },
      { heading: 'Two-Factor Authentication', body: 'Enable TOTP 2FA for your account. Scan the QR code with any authenticator app (Google Authenticator, Authy, 1Password, etc.). Once enabled, every login requires a 6-digit code.' },
      { heading: 'Password change', body: 'Change your dashboard password from the Settings page. Choose a strong password — the dashboard has full control over your system\'s security configuration.' },
    ],
  },
]

export default function Help() {
  const [openIdx, setOpenIdx] = useState(null)

  return (
    <div style={{ padding: 24 }}>

      {/* Header */}
      <div style={{ marginBottom: 24 }}>
        <h2 style={{ fontSize: 18, fontWeight: 700, color: 'var(--text-1)', margin: 0 }}>Help &amp; Documentation</h2>
        <p style={{ fontSize: 13, color: 'var(--text-3)', marginTop: 4 }}>
          Learn what each section of the dashboard does and how to use it effectively.
        </p>
      </div>

      {/* Quick nav chips */}
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginBottom: 24 }}>
        {SECTIONS.map((s, i) => (
          <button key={i}
            onClick={() => setOpenIdx(openIdx === i ? null : i)}
            style={{
              padding: '5px 12px', borderRadius: 99, fontSize: 12, fontWeight: 600,
              cursor: 'pointer', border: '1px solid var(--border-md)',
              background: openIdx === i ? 'var(--accent)' : 'var(--bg-surface)',
              color: openIdx === i ? '#fff' : 'var(--text-2)',
              transition: 'all 0.15s',
            }}>
            {s.icon} {s.title}
          </button>
        ))}
      </div>

      {/* Section cards */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
        {SECTIONS.map((section, i) => (
          <motion.div key={i} className="card"
            style={{ overflow: 'hidden' }}
            initial={{ opacity: 0, y: 6 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.03 }}>

            {/* Section header / toggle */}
            <div
              onClick={() => setOpenIdx(openIdx === i ? null : i)}
              style={{
                display: 'flex', alignItems: 'center', gap: 12,
                padding: '14px 18px', cursor: 'pointer',
                borderBottom: openIdx === i ? '1px solid var(--border)' : 'none',
              }}>
              <span style={{ fontSize: 20, flexShrink: 0 }}>{section.icon}</span>
              <div style={{ flex: 1 }}>
                <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--text-1)' }}>
                  {section.title}
                  <span style={{ fontSize: 11, fontWeight: 500, color: 'var(--text-3)', fontFamily: 'var(--font-mono)', marginLeft: 8 }}>
                    {section.path}
                  </span>
                </div>
                <div style={{ fontSize: 13, color: 'var(--text-3)', marginTop: 2 }}>
                  {section.summary}
                </div>
              </div>
              <span style={{ fontSize: 13, color: 'var(--text-3)', flexShrink: 0 }}>
                {openIdx === i ? '▲' : '▼'}
              </span>
            </div>

            {/* Details */}
            <AnimatePresence>
              {openIdx === i && (
                <motion.div
                  initial={{ height: 0, opacity: 0 }}
                  animate={{ height: 'auto', opacity: 1 }}
                  exit={{ height: 0, opacity: 0 }}
                  transition={{ duration: 0.22 }}
                  style={{ overflow: 'hidden' }}>
                  <div style={{ padding: '16px 18px 18px', display: 'flex', flexDirection: 'column', gap: 14 }}>
                    {section.details.map((d, j) => (
                      <div key={j}>
                        <div style={{ fontSize: 12, fontWeight: 700, color: 'var(--accent)', textTransform: 'uppercase', letterSpacing: '0.05em', marginBottom: 4 }}>
                          {d.heading}
                        </div>
                        <p style={{ fontSize: 13, color: 'var(--text-2)', lineHeight: 1.65, margin: 0 }}>
                          {d.body}
                        </p>
                      </div>
                    ))}
                  </div>
                </motion.div>
              )}
            </AnimatePresence>

          </motion.div>
        ))}
      </div>

      {/* Footer */}
      <div style={{ marginTop: 24, padding: '16px 18px', borderRadius: 10, background: 'var(--bg-surface)', border: '1px solid var(--border)' }}>
        <p style={{ fontSize: 13, color: 'var(--text-3)', margin: 0, lineHeight: 1.6 }}>
          Need more help? Check the{' '}
          <a href="https://github.com/fahimrahmanbooom/ai-sbc-security" target="_blank" rel="noopener noreferrer"
            style={{ color: 'var(--accent)', textDecoration: 'none', fontWeight: 600 }}>
            GitHub repository
          </a>{' '}
          for full documentation, issue tracking, and community discussions. Found a bug? Open an issue — contributions are very welcome.
        </p>
      </div>
    </div>
  )
}
